language: node_js
node_js:
 - "node"
deploy:
  provider: heroku
  api_key:
    secure: OEjXW/Mf9vJc2IhVSXE1z2NMajjJxQ3m8OQEzPIBSdrkLHA9HNgCO5vTB28Vxsi4Y7XiFAK/1k+Cj8tUWRLX1xrl45WP/425kETlz6cqBvic6K2+XmZb0ykSKvwvbP8eOxOYCN7ZZyJIzdK34i5CXkGWHHLq24Z8VJFibQjgoGKKr87riNmB4SjwVoI2++3OUE/9uzRxRu3mRhl0WySp0anMXKBMYFeYqT8u7FSIgEHVBXBBe8Bc1dE0DbbjXGkyvRUE3/bfxMKJw/cZfrc6KRDpU+NKJSFTW66NkBVa6USF2g1nc9ksFUW8tUEzaEu71L99btRY7Hn97aHk/iHrxzSuYni3N3CU1bLDjPZrIUym8yY7OitfCKuVShWWzEJn4oPWF4JqbcYjwGDhu/UCEX0zbSux0idCG1/Rhf0OR94zazBU7heIm+JOQSqq79Q5dqFgOGsXvyRo2nZuMJ+8+6Yd++nMAT5XhZjxWvt0RUXOvR87PlbnxuG1Riwi6xAd6FhmVoO+AOQzTxNdXuztbpE9+stuA/unCBWPQTocWrJT9b/WibihSa2y5xLNjzik0Jjt0P3KRLfwMnS3qxHPke8SvXzZZbrfrEI/1DJfPD9c29aywb3lq/jpqUDhfLoOwwWOSvTfW19ZyHjTLoF8jSD7RuPgChEqFhiqABnL0e4=
  app: vast-forest-37635
