language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: TA/odlVAcyGX7FO4jgqHc/iraQsSn56RAW08opMZYC9Q91yknAMrtofgpnsFtsjK9ZP1DYjcxKPu/I0m8YN0o68OajFdWfdi02ayHB8LCqvf0zuEC9KaJUoobIvp2k2sMSMzRScN/LgeCDbr++rRCUDhB9Q3TpqnN9H7R/R6rnW2Ow1LKyautSMRLmQxU6w9yy7aty7l5kwAtHLZ74OAO7b60Jz7Ho7hx4Gz4g3pwGK+XeOkMbBWHqFsatmmMTZnqTAjQB1im94J3EI+TaDLMoy69L7OUT900dVD32b9fAuMAhuXCfICNuo5ei9Awq8Q9Q8tfPt5lVpll1ReLLGbV3DZqqZucyJUXaRPpqp0iTM0DXSyOYwxlYfAckxE0XxhbQkKEnMNwV2Wn322LMS2FrYy8s7V4gfW2gcTTu9EHlUQzK/4k4ohnyMx0HcKlgRv0tio7gFoEiQPmiPgjcPz0YWBNHsSBXOSHbjMK0syErgHCdXgjdRdE4wq11U2E2fB968VBWA9t/0VeGJwO/fu9FsLzsU5Lt1QbKV4DRXuaZozX1DHoyC9NoDOiskFLdZdLvTVU/VYrKGSred2RiuixrqEZE7i3IFxEJkuzXfz8lnjbLQzO8ta7EKrzH00t/9qiCFHMjv/jmgaF8jVGSfTroYA74v759bd3oodF5S7GDs=
  app: vast-forest-37635
